# Generated by Django 4.2.21 on 2025-08-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["created"]},
        ),
    ]
